# Nome do workflow
name: Hello World
on:
  workflow_dispatch:
jobs:
  # Nome do job
  hello-world:
    # Definição do SO que vai executar o job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
