name: Schedule
on:
  schedule:
    - cron: '* * * * *' # A cada minuto
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: 'echo "Horarial atual: $(date)"'